# Generated by Django 4.0.1 on 2022-02-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameraterapi', '0003_alter_game_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergamerating',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usergamerating',
            name='rating',
            field=models.FloatField(),
        ),
    ]
