# Generated by Django 4.0.2 on 2022-02-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameraterapi', '0005_remove_usergameimage_url_usergameimage_action_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergameimage',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
